[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
  h2zero/NimBLE-Arduino@^1.4.3
  t-vk/ESP32 BLE Keyboard@^0.3.2
  adafruit/Adafruit NAU7802 Library@^1.0.4
  adafruit/Adafruit BusIO
build_flags =
  -DUSE_NIMBLE
  -DCORE_DEBUG_LEVEL=0
